apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-backend
  template:
    metadata:
      labels:
        app: redis-backend
    spec:
      containers:
        - name: redis-backend
          image: redis
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-backend-service
spec:
  ports:
    - port: 6379
  selector:
    app: redis-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: redis-app
          image: nikxgupta/redis-app:v1
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: DEV
          - name: RedisConnection
            value: "redis-backend-service"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: redis-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: redis-app
